### ISSUE TITLE
Error: No controller: valFormManager

### ISSUE THREAD

**Issue by fabianScout** [EndzoneSoftware/uSplit#11]
Hello,

installed uSpilt succesfull and it's running now.
But in browser console we get following error when we click the A/B testing node in the content tree:

angular.min.js:63 Error: No controller: valFormManager
    at i (http://ourDomain.com/umbraco/lib/angular/1.1.5/angular.min.js:42:336)
    at http://ourDomain.com/umbraco/lib/angular/1.1.5/angular.min.js:42:404
    at Array.forEach (native)
    at n (http://ourDomain.com/umbraco/lib/angular/1.1.5/angular.min.js:6:470)
    at i (http://ourDomain.com/umbraco/lib/angular/1.1.5/angular.min.js:42:381)
    at k (http://ourDomain.com/umbraco/lib/angular/1.1.5/angular.min.js:44:463)
    at e (http://ourDomain.com/umbraco/lib/angular/1.1.5/angular.min.js:40:139)
    at http://ourDomain.com/umbraco/lib/angular/1.1.5/angular.min.js:39:205
    at http://ourDomain.com/umbraco/lib/angular/1.1.5/angular.min.js:162:213
    at Object.fn (http://ourDomain.com/umbraco/lib/angular/1.1.5/angular.min.js:90:12) <li ng-class="{'tab-error': tabHasError}" ng-repeat="tab in visibleTabs" val-tab="" class="ng-scope">

Tested in Chrome, IE and FF.

It's okay? Because page seems to work :) Also switching the tab to "Instuctions" works.

**Comment by ondrejpialek** [comment]
Hi @fabianScout, what version of Umbraco is this? 

There is no reference to `valFormManager` in our code base and the call stack does not reference uSplit either. Are you sure it comes from uSplit?

**Comment by fabianScout** [comment]
Umbraco version 7.5.3 assembly: 1.0.6092.24019

I only get this message if I click the A/B Testing node.
On a machine of a colleague I'm not able to reproduce this error. He has excactly the same codebase but no uSplit package.

**Comment by fabianScout** [comment]
Found a solution. Last answer on this page: https://our.umbraco.org/forum/developers/extending-umbraco/61679-Adding-a-tab-custom-section-angular-errors 

Added **val-form-manager** to the form  ~/App_Plugins/uSplit/backoffice/abtesting/dashboard.html

**Comment by ondrejpialek** [comment]
Hi @fabianScout, thanks a lot for that! I just finished installing uSplit on that particular version and will verify if that fixes it. If it does I will add it to the source code and release a new version soon.

**Comment by ondrejpialek** [comment]
Hello @fabianScout, that indeed solved the JS error, thanks a lot for the contribution! A new version will be available on NuGet soon.
