### ISSUE TITLE
Nuget package not installable for Umbraco 7.5

### ISSUE THREAD

**Issue by CheeseSucker** [EndzoneSoftware/uSplit#14]
The package has a dependency which does not include 7.5.1 and above:
UmbracoCms.Core (>= 7.3.0 && <= 7.5.0)

Error from Nuget:
>Attempting to resolve dependencies for package 'Endzone.uSplit.1.0.101' with DependencyBehavior 'Lowest'
> Unable to find a version of 'UmbracoCms.Core' that is compatible with 'Endzone.uSplit 1.0.101 constraint: UmbracoCms.Core (>= 7.3.0 && <= 7.5.0)'.

Affected package versions:
  -  v1.0.101
  -  v1.0.97
  -  v1.0.93

**Comment by ondrejpialek** [comment]
Hi @CheeseSucker,

thanks for pointing that out, fixed in https://github.com/EndzoneSoftware/uSplit/commit/1d1947d7da05c6e655e2dcede5350488376b1d1f

Should be on NuGet shortly.

Cheers,
Ondrej.
