### ISSUE TITLE
Avoid setting request.PublishedContent in catch statement in ExperimentsPipeline 

### ISSUE THREAD

**Issue by hakon-knowit** [EndzoneSoftware/uSplit#16]
When uSplit throws an exception in ExperimentsPipeline it [resets the value of request.PublishedContent](https://github.com/EndzoneSoftware/uSplit/blob/master/src/Endzone.uSplit/Pipeline/ExperimentsPipeline.cs#L48). Umbraco then sets TemplateModel to null. [See property setter in PublishedContentRequest](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/Routing/PublishedContentRequest.cs#L188)

This causes Umbraco to serve completely empty responses to users on our website.

Proposed solution:
  1. Only set PublishedContent if it is different from original value
  2. Run [request.TrySetTemplate](https://github.com/EndzoneSoftware/uSplit/blob/master/src/Endzone.uSplit/Pipeline/ExperimentsPipeline.cs#L106) after setting property

**Comment by ondrejpialek** [comment]
Should be fixed. Thanks @hakon-knowit!
