### ISSUE TITLE
Issue with deleting an experiment version 1.0.114.0

### ISSUE THREAD

**Issue by davidmcg1985** [EndzoneSoftware/uSplit#21]
Hi,

Is there a known issue in version 1.0.114.0 when deleting an experiment, a 404 is thrown on the backoffice/uSplit/Manage/DeleteExperimentAsync/{id} call? 

Version of Umbraco I am using is 7.5.9

Cheers,

David

**Comment by ondrejpialek** [comment]
Hi @davidmcg1985, sorry 1.0.x is no longer supported. If you experience any issues with the newer version please do let us know!
