### ISSUE TITLE
Can't use custom models with uSplit

### ISSUE THREAD

**Issue by ptilsed** [EndzoneSoftware/uSplit#22]
Hi,

After installing uSplit onto one of our sites to test the basic functionality we hit an error on a page where we use a custom model in the template. This set up is commonplace and almost default given Models Builder is now part of the core. 

After a bit of digging, I found the error was being caused by uSplit passing in its own custom model to the page in order to render the content. I think that to make uSplit relevant to newer Umbraco builds it needs to be able to work with custom models and not just its own iPublishedContent model.

Cheers,

Paul

**Comment by ondrejpialek** [comment]
Thanks @ptilsed , merged and will be released soon
