### ISSUE TITLE
Does uSplit works with multiple sites?

### ISSUE THREAD

**Issue by mvanhelmont** [EndzoneSoftware/uSplit#26]
Is it posible to have a multi site setup for uSplit? Multiple sites under de same Umbraco installation!

The Analytics account has multiple property's all under that account.

**Comment by ondrejpialek** [comment]
Hello @mvanhelmont, yes that is possible, we are using it ourselves on an Umbraco installation that hosts over 300 sites :)

**Comment by mvanhelmont** [comment]
Nice any guides how i need to setup? Or how does usplit knows in which property he needs to create the experiment?

**Comment by ondrejpialek** [comment]
Guides for multi-property or in general?

Multiple properties see: https://github.com/EndzoneSoftware/uSplit/pull/18
General: http://endzonesoftware.com/usplit/installing-usplit/

**Comment by mvanhelmont** [comment]
thanks this is what i was looking for
