### ISSUE TITLE
SEO optimization and more

### ISSUE THREAD

**Issue by alecrt** [EndzoneSoftware/uSplit#5]
First of all: great piece of software guys. 
Very easy to set up and use.

Just two questions: 

1. Is it possible to prevent variation pages to be reached by their own url?
This is not a good thing for SEO: crawler can reach the pages and find duplicate content.

2. I suggest hiding the variantions folder. Variations node should be editable only from experiment page. It would make everything easier to understand.

What do you think about?

**Comment by ondrejpialek** [comment]
Hi @alecrt,

thanks for the compliments and for the great suggestions!

1. I suggest you check our [user guide](http://www.happyporch.com/running-ab-experiments-like-pro-usplit/), the section titled _Creating a variations folder (optional)_
  - Basically create a new "folder" under the root of your site and store all your variations there (simply move them there)
  - Then add a URL rewrite rule to block all content under the variations folder
2. You have a good point there. I have created a new issue here to track it separately. Check #6 in a few minutes for a reply.

Let me know if you are having problems getting the above sorted ;)

Best Regards,
Ondrej.

**Comment by alecrt** [comment]
Hi @ondrejpialek,

thanks for your reply.

For the very first point i had already created the variations folder under the root but for some strange reasons the url of the variations inside it doesn't inherit the parent folder url segment.

i.e. 
Variation folder name: "Variantion" -> url-> "/variations"
Variation node name: "PageB"
Url expected for the variation node: /variations/pageb
Umbraco generated url: /pageb

Any ideas?

p.s. About hiding the variations container folder: i will fork the project and try to give my contribute after completing a big project i'm involved in at the moment. :D

**Comment by barryokane** [comment]
Hi @alecrt,

Why do you need the Url for the variation?  When the test is running your users should see their variation, but not be redirected to another URL.

Barry

**Comment by barryokane** [comment]
NB: regarding the "variations" folder not appearing in URLs: this may be due to Umbraco's umbracoHideTopLevelNodeFromPath setting (https://our.umbraco.org/documentation/reference/config/webconfig/)
