### ISSUE TITLE
Republish entire site gone

### ISSUE THREAD

**Issue by 2014amja** [EndzoneSoftware/uSplit#7]
Right click at "Content" in the content section is used to present a menu to "Republish entire site" This is gone

**Comment by ondrejpialek** [comment]
Hi @2014amja, thanks a lot for loggin this issue and issue #8. Both look pretty severe but I have some ideas already what might be the culprit. I will review both issues tomorrow morning and either fix them or update these issues with further details. Thanks a lot for taking the time reporting these and apologies for the inconveniecne cause.

**Comment by ondrejpialek** [comment]
Hello @2014amja,

I have taken a clean install of Umbraco and installed uSplit on top of it and both "Republish entire site" and "Recycle Bin" are still accessiblem see image:

![clean-install](https://cloud.githubusercontent.com/assets/580850/20346732/093fe36e-abfe-11e6-9b42-15f28f04f265.png)

Could you please tell me what plugins you are have installed and what method did you use to install uSplit (NuGet or via backoffice)? Any other information you may have would be useful as well.

Cheers,
Ondrej.

**Comment by 2014amja** [comment]
Hi 
I did install via uSplit nuget. 
I have theese pacakage installed via nuget:

- Epiphany.SeoMetadata
- CMUmbracoTools
- Nibble.Umbraco.PageNotFoundManager
- Archetype

Installed local:

- The Dashboard
- Optimus.Core
- Optimus.Providers.TypeScript
- Optimus.Providers.Less
- Umbraco Forms
- reCAPTCHA field for Umbraco Forms
- AutoRotate
- SafeMailLink

I will try to recreate the the issue.

**Comment by 2014amja** [comment]
Hi Ondrei
I have  dona a clean install of umbraco and install all the packages, ind i can´t reproduce the error.
is it possible that the naming og doctypes and properties can have some influence?.

René

**Comment by ondrejpialek** [comment]
@2014amja I can't think of a reason why names would affect the behaviour. In Umbraco you can affect the way menus and the trees are generated, even for content that is not part of your package (that way you can extend the default context menu of content nodes, or add functionality to some other plugin).

My guess would be that there is some login inside your app that uses the following events and somehow hides those two options:

```
 TreeControllerBase.TreeNodesRendering += TreeControllerBase_TreeNodesRendering;
TreeControllerBase.MenuRendering += TreeControllerBaseOnMenuRendering;
```

This wouldn't explain why it stopped working when you installed uSplit though. I would start by comparing the bin directory of your website with what you got through that clean install with all the 
plugins, to check if perhaps there is a rougue library that contains some logic to that effect. Maybe you could have someting in your App_Code or part of your project and compiled that affects the behaviour? You can register a listener yourself and add a breakpoint in it, and check at runtime if there are other listeners.

I will be closing these issues now but if you manage to reproduce it I will reopen them.
