### ISSUE TITLE
Recycle bin is gone from content section

### ISSUE THREAD

**Issue by 2014amja** [EndzoneSoftware/uSplit#8]
The "recycle bin" is gone after installing uSplit.

**Comment by 2014amja** [comment]
![fireshot pro screen capture 149 - content - hrjoergensen_local - hrjoergensen_local_umbraco_ _conte](https://cloud.githubusercontent.com/assets/10165132/20140139/de8d9874-a689-11e6-9412-9f7b1e7b6d99.jpg)

**Comment by ondrejpialek** [comment]
Cannot reproduce, see #7 for details. Waiting for further feedback.
