### ISSUE TITLE
Setup uSplit without authentication?

### ISSUE THREAD

**Issue by fabianScout** [EndzoneSoftware/uSplit#9]
Hello, 
if we try to setup uSplit in our test environment we struggle with the Google API Credentials. Our local uri is umbraco.our-domain.de.local and staging server is only available with umbraco.our-domain.stage.
But these uri's are not allowed for the Authorised redirect URIs and we get following exception from the API manager when we try to save:
Invalid Redirect: http://umbraco.our-domain.de.local must end with a public top-level domain (such as .com or .org). 

So, we can't save the URI in API Manager Credentials and only configure the Credentials for our live URI.
If we open the uSplit - A/B testing page in umbraco on our local machine we get two organge warnings:
1. Warning! This site is not authenticated with the Google API.
2. Warning! Object reference not set to an instance of an object..

Is there a way to get it running on our local machines and stage environment with these special URIs we have?

Thanks.
Regards,
Fabian

**Comment by ondrejpialek** [comment]
Hello @fabianScout,

unfortunately this is a limitation of Google API, one however that is easy to work around.

If you want to test uSplit on your local or stating environment, and use custom TLD, you need to do the following:

- add additional IIS binding for a domain that ends with ".com". You do not need to own this domain, test.com is valid for instance.
- add a host file entry pointing this domain to the IP address of your staging server, or poining to 127.0.0.1 if you want to test uSplit locally.
- enter this custom domain (followed by the correct path) into Google API.

This will be sufficient as when you authenticate with google, it will redirect you to the custom domain, but your computer will navigate to the IP address set in your hosts file. Note however that authentication will only work on those PCs where the hosts entry is present.

Hope this helps,
Ondrej.

**Comment by fabianScout** [comment]
Hi Ondrej,

worked for me. Now we can test uSplit local.

Thanks.
Fabian
